services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: workshop
      POSTGRES_USER: workshop
      POSTGRES_PASSWORD: workshop
    ports:
      - "5432:5432"
    volumes:
      - workshop_db:/var/lib/postgresql/data
volumes:
  workshop_db:
